package parser;

public enum Sym{
    EOF,COULEUR, INT, OPERATEUR, POINTVIRGULE, BEGIN, END, IF, THEN, ELSE, LPAR, RPAR, DRAWCIRCLE, FILLCIRCLE, FILLRECT, DRAWRECT, CONST, VAR, BOOLEAN, COMPARATOR, EQ, ASSIGNATION, IDENT, OR,AND, PLUS,MINUS,TIMES,DIV,STRING;
}
