package parser;

public enum Sym{
    EOF,COULEUR, INT, OPERATEUR, POINTVIRGULE, BEGIN, END, IF, THEN, ELSE, LPAR, RPAR, DRAWCIRCLE, FILLCIRCLE, FILLRECT, DRAWRECT, CONST, VAR, BOOLEAN, RELATION, ASSIGNATION, IDENT,STRING;
}
