public enum Sym{
	COULEUR, INT, OPERATEUR, POINTVIRGULE, BEGIN, END, IF, THEN, ELSE, LPAR, RPAR, DRAWCIRCLE, FILLCIRCLE, FILLRECT, DRAWRECT, CONST, VAR,BOOLEAN, ELSEIF, RELATION, ASSIGNATION, STRING;
}